name: jupyterlab_graphviz
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - scikit-learn
  - sympy
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - rise
  - appmode
  - pip:
    - lux-api
    - jupyter-contrib-nbextensions
    - nbgitpuller
