name: jupyterlab_graphviz
channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - distributed
  - graphviz
  - jupyterlab >=0.32,<0.33
  - networkx
  - nltk
  - nodejs
  - pydot
  - pydotplus
  - pygraphviz
  - pylint
  - python >=3.6,<3.7
  - python-graphviz
  - scikit-learn
  - sympy
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - rise
  - pip:
    - pycallgraph
    - transitions
    - jupyter-contrib-nbextensions



      
